openapi: 3.0.0
info:
  title: Destination
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/destinations:
    get:
      tags:
        - General
      summary: Get List All Destination
      responses:
        '200':
          description: OK
          headers:
            cache-control:
              schema:
                type: string
                example: no-cache, private
            content-type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                meta:
                  code: 200
                  status: success
                  message: Success
                data:
                  data:
                    - id: 1
                      created_at: '2021-06-17T13:57:07.000000Z'
                      updated_at: '2021-06-21T07:08:58.000000Z'
                      title: Kota Tuaxx
                      description: >-
                        Kota tua di Jakarta, yang juga bernama Kota Tua,
                        berpusat di Alun-Alun Fatahillah, yaitu alun-alun yang
                        ramai dengan pertunjukan rutin tarian tradisional.
                        Museum Sejarah Jakarta adalah bangunan era Belanda
                        dengan lukisan dan barang antik, sedangkan Museum Wayang
                        memamerkan boneka kayu khas Jawa. Desa Glodok, atau
                        Chinatown, terkenal dengan makanan kaki lima, seperti
                        pangsit dan mi goreng. Di dekatnya, terdapat sekunar dan
                        kapal penangkap ikan di pelabuhan Sunda Kelapa yang
                        kuno.xx
                      link_maps: https://goo.gl/maps/vrfprjpj8cRQ3EMh8xx
                      deleted_at: null
                      images:
                        - id: 2
                          id_destinations: 1
                          link_image: >-
                            assets/image/destination/gvV3r8HWbJEi6HFA6nR7PZr7iHdT8JajKinES5xl.jpg
                          created_at: '2021-06-21T08:28:35.000000Z'
                          updated_at: '2021-06-21T08:28:35.000000Z'
                          deleted_at: null
                    - id: 3
                      created_at: '2021-06-21T06:27:06.000000Z'
                      updated_at: '2021-06-21T06:27:06.000000Z'
                      title: Borobudur
                      description: >-
                        Borobudur adalah sebuah candi Buddha yang terletak di
                        Borobudur, Magelang, Jawa Tengah, Indonesia. Candi ini
                        terletak kurang lebih 100 km di sebelah barat daya
                        Semarang, 86 km di sebelah barat Surakarta, dan 40 km di
                        sebelah barat laut Yogyakarta.
                      link_maps: https://goo.gl/maps/etAq28AH3bZQNWjj8
                      deleted_at: null
                      images:
                        - id: 1
                          id_destinations: 3
                          link_image: >-
                            assets/image/destination/qK3sZ6C0PwwuD1Teiv587HZJ2mf2OqPmgkCjKqAL.jpg
                          created_at: '2021-06-21T08:23:59.000000Z'
                          updated_at: '2021-06-21T08:23:59.000000Z'
                          deleted_at: null
                    - id: 4
                      created_at: '2021-06-22T04:15:33.000000Z'
                      updated_at: '2021-06-22T04:15:33.000000Z'
                      title: Malioboro
                      description: >-
                        Malioboro adalah nama salah satu kawasan jalan dari tiga
                        jalan di Kota Yogyakarta yang membentang dari Tugu
                        Yogyakarta hingga ke perempatan Kantor Pos Yogyakarta.
                        Secara keseluruhan terdiri dari Jalan Margo Utomo, Jalan
                        Malioboro, dan Jalan Margo Mulyo. Jalan ini merupakan
                        poros Garis Imajiner Kraton Yogyakarta.
                      link_maps: https://goo.gl/maps/jyBs57a4HwY3iRQB7
                      deleted_at: null
                      images: []
  /api/destinations/{id}:
    get:
      tags:
        - General
      summary: Get One Destination
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            cache-control:
              schema:
                type: string
                example: no-cache, private
            content-type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                meta:
                  code: 200
                  status: success
                  message: Success
                data:
                  destination:
                    id: 1
                    created_at: '2021-06-17T13:57:07.000000Z'
                    updated_at: '2021-06-21T07:08:58.000000Z'
                    title: Kota Tuaxx
                    description: >-
                      Kota tua di Jakarta, yang juga bernama Kota Tua, berpusat
                      di Alun-Alun Fatahillah, yaitu alun-alun yang ramai dengan
                      pertunjukan rutin tarian tradisional. Museum Sejarah
                      Jakarta adalah bangunan era Belanda dengan lukisan dan
                      barang antik, sedangkan Museum Wayang memamerkan boneka
                      kayu khas Jawa. Desa Glodok, atau Chinatown, terkenal
                      dengan makanan kaki lima, seperti pangsit dan mi goreng.
                      Di dekatnya, terdapat sekunar dan kapal penangkap ikan di
                      pelabuhan Sunda Kelapa yang kuno.xx
                    link_maps: https://goo.gl/maps/vrfprjpj8cRQ3EMh8xx
                    deleted_at: null
